include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude: [
      lib/**.g.dart,
      lib/configs/dependency_injection/injection.config.dart,
      lib/localization/dart_files/**.dart,
  ]

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
